import { describe, vi, test, expect } from "vitest";
import { llmService } from "../services/llm.service";
import { Response } from "express";

const mockGenerateContentStream = vi.hoisted(() =>
  vi.fn().mockImplementation(async function* () {
    yield { text: "Hello" };
    yield { text: " World" };
  }),
);
vi.mock("@google/genai", () => {
  const GoogleGenAI = vi.fn().mockImplementation(function construct() {
    return {
      models: {
        generateContentStream: mockGenerateContentStream,
      },
    };
  });
  return { GoogleGenAI };
});

describe("llm service", () => {
  test("writes stream of data generated by api on response object", async () => {
    const retrievedChunks = [
      {
        content: "function hello() {}",
        filePath: "src/index.ts",
        startLine: 1,
        endLine: 3,
      },
    ];
    const mockRes = {
      write: vi.fn(),
      end: vi.fn(),
    };
    const result = await llmService(
      "How does auth work?",
      retrievedChunks,
      mockRes as any,
    );
    expect(result).toBeUndefined();
    expect(mockRes.write).toHaveBeenCalledWith(`data: "Hello"\n\n`);
    expect(mockRes.write).toHaveBeenCalledWith(`data: " World"\n\n`);
    expect(mockRes.end).toHaveBeenCalledTimes(1);
  });
  test("writes error message on response object if api throws", async () => {
    mockGenerateContentStream.mockImplementationOnce(async function* () {
      throw new Error("API failed");
    });
    const mockRes = {
      write: vi.fn(),
      end: vi.fn(),
    };
    const retrievedChunks = [
      {
        content: "function hello() {}",
        filePath: "src/index.ts",
        startLine: 1,
        endLine: 3,
      },
    ];
    const result = await llmService(
      "How does auth work?",
      retrievedChunks,
      mockRes as any,
    );
    expect(result).toBeUndefined();
    expect(mockRes.write).toHaveBeenCalledWith(
      "data: Error generating answer\n\n",
    );
    expect(mockRes.end).toHaveBeenCalledTimes(1);
  });
});
